/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERF;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author aruni
 */
public class parkinglotupdate extends javax.swing.JInternalFrame {

    public Connection con = null; 
    public PreparedStatement pst = null;
    ResultSet rs = null;
    
    public parkinglotupdate() {
        initComponents();
        try {
            initComponents();
            con = DriverManager.getConnection("jdbc:mysql://localhost/car_park_management_system", "root", "");
            tableload();
        } catch (SQLException ex) {
            Logger.getLogger(RESERVEUPDATE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tableload() throws SQLException
    {
        String query = "SELECT * FROM lot";
        pst = con.prepareStatement(query);
        rs = pst.executeQuery();
        
        lotdetails.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lotdetails = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lotupdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        showlno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        reservesrcht = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(510, 711));

        lotdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        lotdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lotdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lotdetails);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        lotupdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lotupdate.setText("UPDATE");
        lotupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotupdateActionPerformed(evt);
            }
        });

        jLabel2.setText("LOT NO:");

        showlno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showlno.setText("LOT NO");

        jLabel8.setText("SECTION");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECTION", "A", "B", "C" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH HERE"));

        reservesrcht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservesrchtActionPerformed(evt);
            }
        });
        reservesrcht.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reservesrchtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservesrcht, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservesrcht, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showlno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lotupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lotupdate)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(showlno))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotupdateActionPerformed
      
       
        String ltype = type.getSelectedItem().toString();
       
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update?");
        if(x==0)
        {
            try {           
                String query = "UPDATE lot SET SECTION = '"+ltype+"' WHERE LOT_NO = LOT_NO";
                pst = con.prepareStatement(query);
                pst.execute();
                JOptionPane.showMessageDialog(null, "DATA SUCCESSFULLY UPDATED");
            } catch (SQLException ex) {
                Logger.getLogger(RESERVEUPDATE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            tableload();
        } catch (SQLException ex) {
            Logger.getLogger(RESERVEUPDATE.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        showlno.setText("");
        type.setSelectedItem("SECTION");
   
        
    }//GEN-LAST:event_lotupdateActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void reservesrchtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservesrchtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservesrchtActionPerformed

    public void searchmethod()
    {
    String srch = reservesrcht.getText();
        
        try{
        String sql = "SELECT * FROM lot WHERE LOT_NO LIKE '%"+srch+"%'";
        
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery();
        
        lotdetails.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException ex) {}
        
    }
    private void reservesrchtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reservesrchtKeyReleased
        searchmethod();
    }//GEN-LAST:event_reservesrchtKeyReleased

    private void lotdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lotdetailsMouseClicked
        int r = lotdetails.getSelectedRow();

        String lno = lotdetails.getValueAt(r, 0).toString();
        String ltype = lotdetails.getValueAt(r, 1).toString();
        
        showlno.setText(lno);
        type.setSelectedItem(ltype); 
    }//GEN-LAST:event_lotdetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lotdetails;
    private javax.swing.JButton lotupdate;
    private javax.swing.JTextField reservesrcht;
    private javax.swing.JLabel showlno;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
